export { default as Header } from './Header'
export { default as Main } from './Main'
export { default as About } from './About'
export { default as Galery } from './Galery'
export { default as Footer } from './Footer'
export { default as Copyright } from './Copyright'